steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_AVAILABLE_REPORTS=${_VITE_AVAILABLE_REPORTS}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jaba-reports:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/jaba-reports:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/jaba-reports:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/jaba-reports:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jaba-reports'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jaba-reports:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/jaba-reports:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/jaba-reports:latest'

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _VITE_AVAILABLE_REPORTS: ''

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
